### PR TITLE
V0.5.1

### PR DESCRIPTION
**Pull request by nmahendru**
best effort zeroize.

### CODE REVIEW

**Review by andersk — COMMENTED** [review]
This would make GMP slower for *all* use cases.

* Non-cryptographic applications: slower for no reason.
* Cryptographic operations on public data (e.g. signature verification): slower for no reason.
* Cryptographic operations on secret data running on adequately secure systems: slower for no reason.
* Cryptographic operations on secret data running on systems so horrendously insecure that an attacker will have direct read access to freed memory: reconsider your life choices—but also this isn’t a solution, since many GMP functions other than `__gmpz_clear` perform reallocations, and also your OS might swap your memory out to disk before you can clear it.

This does not belong in general purpose mathematical bindings. There are dedicated cryptographic libraries that deal with securing secrets, and if you’re writing one of those, you should not be using GMP. If you still think you want this functionality with GMP, I suggest putting it in a separate wrapper library.

**Comment by nmahendru** [comment]
> This would make GMP slower for _all_ use cases.
> 
> * Non-cryptographic applications: slower for no reason.
> * Cryptographic operations on public data (e.g. signature verification): slower for no reason.
> * Cryptographic operations on secret data running on adequately secure systems: slower for no reason.
> * Cryptographic operations on secret data running on systems so horrendously insecure that an attacker will have direct read access to freed memory: reconsider your life choices—but also this isn’t a solution, since many GMP functions other than `__gmpz_clear` perform reallocations, and also your OS might swap your memory out to disk before you can clear it.
> 
> This does not belong in general purpose mathematical bindings. There are dedicated cryptographic libraries that deal with securing secrets, and if you’re writing one of those, you should not be using GMP. If you still think you want this functionality with GMP, I suggest putting it in a separate wrapper library.

Thanks @andersk. I totally agree this does not provide a 100 % guarantee that the memory is cleared. 
I also agree that gmp is not the best choice but a make do at best.

This PR is a best effort approach at best. I'll try to put a feature flag around it so that it does not slow down the normal use case. Will that be good ?

**Comment by andersk** [comment]
A feature flag isn’t the right solution—[features are additive](https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/features.md#feature-unification), so that would still affect all uses of GMP in a program if the feature is turned on by *any* library that the program uses.

The role of a binding crate like `gmp` is to be a thin wrapper around the underlying library, and not to add extra custom functionality for a minority of users.

A better solution is to create a new crate (`zeroized-gmp`?) that wraps this one, with its own type (`ZeroizedMpz`?) that wraps `Mpz`, with its own `Drop` implementation. If possible, that type should only expose operations from the base `Mpz` type that are known not to reallocate, or reimplement them in a way that avoids reallocation.

**Comment by nmahendru** [comment]
@andersk alright!

**Pull request closed without merging**
